name: Scrape and generate feed

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12.4' 
        cache: 'pip'
    - name: Install dependencies & Run Script
      run: |
        pip install -r requirements.txt
        python scrape.py
    - name: Commit changes
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "updater"
        git add **
        git commit -m "Update feed"
        git push
      env:
        github_token: ${{ secrets.GITHUB_TOKEN }}
